"""empty message

Revision ID: b9cb0b9d70e6
Revises: 
Create Date: 2021-06-17 21:01:46.265462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9cb0b9d70e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('picture', sa.String(length=800), nullable=True),
    sa.Column('activate', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('picture', sa.String(length=800), nullable=True),
    sa.Column('stars', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('cellphone', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('activate', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cellphone')
    )
    op.create_table('statistics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('activate', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id', 'id_user')
    )
    op.create_table('teams_players',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_team', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('activate', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_team'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id', 'id_team', 'id_user')
    )
    op.create_table('matches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_team_one', sa.Integer(), nullable=False),
    sa.Column('id_team_two', sa.Integer(), nullable=False),
    sa.Column('match_status_team_one', sa.String(length=25), nullable=True),
    sa.Column('match_status_team_two', sa.String(length=25), nullable=True),
    sa.Column('match_date', sa.DateTime(), nullable=True),
    sa.Column('activate', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_team_one'], ['teams_players.id'], ),
    sa.ForeignKeyConstraint(['id_team_two'], ['teams_players.id'], ),
    sa.PrimaryKeyConstraint('id', 'id_team_one', 'id_team_two')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matches')
    op.drop_table('teams_players')
    op.drop_table('statistics')
    op.drop_table('users')
    op.drop_table('teams')
    # ### end Alembic commands ###
